# Generated by Django 6.0.6 on 2026-06-07 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリー名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('icon', models.CharField(default='💬', max_length=10, verbose_name='アイコン（絵文字）')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('pro_label', models.CharField(default='賛成', max_length=50, verbose_name='賛成側名称')),
                ('con_label', models.CharField(default='反対', max_length=50, verbose_name='反対側名称')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='セッションキー')),
                ('author_name', models.CharField(default='匿名', max_length=50, verbose_name='投稿者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debates', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debates', to='debates.category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '討論',
                'verbose_name_plural': '討論',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('side', models.CharField(choices=[('pro', '賛成'), ('con', '反対')], max_length=3, verbose_name='立場')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='セッションキー')),
                ('author_name', models.CharField(default='匿名', max_length=50, verbose_name='投稿者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='debates.debate', verbose_name='討論')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='セッションキー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='debates.post', verbose_name='投稿')),
            ],
            options={
                'verbose_name': 'いいね',
                'verbose_name_plural': 'いいね',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='セッションキー')),
                ('author_name', models.CharField(default='匿名', max_length=50, verbose_name='投稿者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='debates.comment', verbose_name='親コメント')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='debates.post', verbose_name='投稿')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['-created_at'], name='debates_deb_created_159436_idx'),
        ),
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['category'], name='debates_deb_categor_23127e_idx'),
        ),
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['is_active'], name='debates_deb_is_acti_2b85bb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['debate', 'side'], name='debates_pos_debate__dec3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='debates_pos_created_d77f46_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'session_key'], name='debates_lik_post_id_008caf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent'], name='debates_com_post_id_49e2dd_idx'),
        ),
    ]
